### PR TITLE
Add models for progress

### PR DESCRIPTION
**Pull request by raulingg**
:pray:  Review before Laboratoria/schemas#13, because this PR depends on it

### CODE REVIEW

**Comment by arku** [comment]
@raulingg Is this ready for a review?

Btw, can you fix the failing tests when you get a chance?

**Comment by raulingg** [comment]
> @raulingg Is this ready for a review?
> 
> Btw, can you fix the failing tests when you get a chance?

Actually it is ready for review, but I can fix the failing tests because the dependencies that comes from  https://github.com/Laboratoria/schemas/pull/13

**Comment by raulingg** [comment]
:pray: Review before https://github.com/Laboratoria/schemas/pull/13, because this PR depends on it

**Comment by MaiaRojas** [comment]
Se cierra por que esta inactivo :slightly_smiling_face:  @raulingg

**Pull request closed without merging**
